<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="PostJsonDemo"
           tests="3"
           failures="1"
           errors="0"
           skipped="0"
           time="0.544">
  <properties />
            <testcase name="LoginByFail2" time="0.104" classname="com.api.test.PostJsonDemo">
                <failure type="java.lang.Exception"
                  message="expectedValue doesn&apos;t match actualValue,actual Value is :用户名或者密码错误; expected Value is :用户名为空"
              >
<![CDATA[java.lang.Exception: expectedValue doesn't match actualValue,actual Value is :用户名或者密码错误; expected Value is :用户名为空
  com.api.utils.Checker.verify(Checker.java:65)
  com.api.utils.Checker.verifyXpath(Checker.java:48)
  com.api.test.PostJsonDemo.LoginByFail2(PostJsonDemo.java:40)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
  org.testng.SuiteRunner.run(SuiteRunner.java:364)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
  org.testng.TestNG.runSuites(TestNG.java:1049)
  org.testng.TestNG.run(TestNG.java:1017)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="LoginBySuccess" time="0.344" classname="com.api.test.PostJsonDemo" />
                <testcase name="LoginByFail1" time="0.096" classname="com.api.test.PostJsonDemo" />
      
</testsuite>
